# Generated by Django 4.1.7 on 2023-04-07 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_propertycomment_rating_usercomment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycomment',
            name='timetag',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='comment date'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='timetag',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='comment date'),
        ),
    ]
