# Generated by Django 4.1.7 on 2023-04-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_propertycomment_timetag_usercomment_timetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycomment',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
