# Generated by Django 4.1.7 on 2023-04-10 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_propertycomment_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
