# Generated by Django 4.1.7 on 2023-04-08 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_bath_alter_property_bed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='type',
        ),
        migrations.DeleteModel(
            name='HouseType',
        ),
    ]
