# Generated by Django 4.1.7 on 2023-04-09 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_property_type_delete_housetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(default='icons/housetype/default.jpg', upload_to='icons/housetype/')),
            ],
            options={
                'verbose_name': 'House Type',
                'verbose_name_plural': 'House Types',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.housetype'),
            preserve_default=False,
        ),
    ]
