# Generated by Django 4.1.7 on 2023-04-09 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='type',
        ),
        migrations.DeleteModel(
            name='HouseType',
        ),
    ]
