# Generated by Django 4.1.7 on 2023-04-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='accessibility',
            field=models.ManyToManyField(blank=True, null=True, to='property.accessibility'),
        ),
    ]
