# Generated by Django 4.1.7 on 2023-04-09 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_listing_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='host',
        ),
    ]
