# Generated by Django 4.1.7 on 2023-04-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_listing_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='host',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
